// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaIheY71D9Lr-fLgG7TiocsZqhYUBkS7k',
    appId: '1:397453461993:web:4ac79f7c36d04d354ae378',
    messagingSenderId: '397453461993',
    projectId: 'my-goood-note',
    authDomain: 'my-goood-note.firebaseapp.com',
    storageBucket: 'my-goood-note.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vOklWyEPT0Fu-s2rtGf5JaSUag26MQE',
    appId: '1:397453461993:android:68a791bf1576c5f24ae378',
    messagingSenderId: '397453461993',
    projectId: 'my-goood-note',
    storageBucket: 'my-goood-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1_CRc6lfWQ2TddqRbDDiGSkvbjER78kc',
    appId: '1:397453461993:ios:992c21de8aff2de04ae378',
    messagingSenderId: '397453461993',
    projectId: 'my-goood-note',
    storageBucket: 'my-goood-note.appspot.com',
    iosClientId:
        '397453461993-kuka4q39807hubdfoml2ahr0dl0nokjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1_CRc6lfWQ2TddqRbDDiGSkvbjER78kc',
    appId: '1:397453461993:ios:992c21de8aff2de04ae378',
    messagingSenderId: '397453461993',
    projectId: 'my-goood-note',
    storageBucket: 'my-goood-note.appspot.com',
    iosClientId:
        '397453461993-kuka4q39807hubdfoml2ahr0dl0nokjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
